### ISSUE TITLE
Determine appropriate home for these resources

### ISSUE THREAD

**Issue by serahkiburu** [carpentries/community-development#1]
Some local community building resources can be found in the [Carpentries Cookbook](http://cookbook.carpentries.org). Information about regional communities in The Carpentries can also be found in [The Carpentries Handbook](https://docs.carpentries.org/topic_folders/regional_communities/index.html), as well as [on the main Carpentries website](http://carpentries.org/regionalcoordinators/). We need to determine what a good central location for all local and regional community resources is - both resources for growing and sustaining these communities, and information about these communities for new and existing members.

**Comment by acrall** [comment]
We will now be using this repository to capture the resources that are available, including a Zotero collection in The Carpentries library. We renamed it "community-development" to give it a broader focus than its original intent. A subcommunity registry is being added to the new website that will include details on each subcommunity. Once available, we will also link it here. As the number of resources grow, we may restructure things, but closing this issue for now
